export type PlantCategory = "Interior" | "Exterior" | "Flores" | "Huerto";
export interface Plant { id:string; name:string; botanical:string; category:PlantCategory; price:number; image:string; light:string; water:string; season:string; difficulty:string; petNote:string; description:string; }
export const CATEGORIES = ["Todas", "Interior", "Exterior", "Flores", "Huerto"] as const;
export const PLANTS: Plant[] = [
 {id:"lavanda",name:"Lavanda inglesa",botanical:"Lavandula angustifolia",category:"Exterior",price:5990,image:"https://images.unsplash.com/photo-1560336767-c82176dd9f7f?auto=format&fit=crop&w=1200&q=82",light:"Sol directo",water:"Bajo · cada 7–10 días",season:"Floración primavera–verano",difficulty:"Fácil",petNote:"Precaución con mascotas si la ingieren.",description:"Aromática, resistente y muy visitada por polinizadores. Prefiere sustrato drenante y tolera bien los veranos secos una vez establecida."},
 {id:"hortensia",name:"Hortensia",botanical:"Hydrangea macrophylla",category:"Flores",price:8990,image:"https://images.unsplash.com/photo-1749891757829-b916bbc27c16?auto=format&fit=crop&w=1200&q=82",light:"Semisombra · sol de mañana",water:"Alto · 2–3 veces por semana",season:"Floración primavera–verano",difficulty:"Intermedia",petNote:"Tóxica para perros y gatos si se ingiere.",description:"Un clásico de jardín de flor abundante. Necesita suelo húmedo, rico y con buen drenaje; agradece protección durante las tardes calurosas."},
 {id:"geranio",name:"Geranio zonal",botanical:"Pelargonium zonale",category:"Flores",price:3990,image:"https://images.unsplash.com/photo-1559637685-9f884287f1cb?auto=format&fit=crop&w=1200&q=82",light:"Sol o semisombra",water:"Medio · al secarse la superficie",season:"Primavera a otoño",difficulty:"Fácil",petNote:"Tóxico para perros y gatos si se ingiere.",description:"Color duradero para macetas y jardineras. Florece durante meses con buena luz y riego moderado, evitando siempre el encharcamiento."},
 {id:"echeveria",name:"Echeveria",botanical:"Echeveria elegans",category:"Exterior",price:3490,image:"https://images.unsplash.com/photo-1724148893915-c3e5370067d5?auto=format&fit=crop&w=1200&q=82",light:"Luz intensa · sol suave",water:"Muy bajo · dejar secar",season:"Todo el año",difficulty:"Muy fácil",petNote:"Generalmente considerada no tóxica.",description:"Suculenta compacta en forma de roseta. Requiere sustrato mineral de drenaje rápido y protección frente a lluvias prolongadas y heladas fuertes."},
 {id:"monstera",name:"Monstera",botanical:"Monstera deliciosa",category:"Interior",price:12990,image:"https://images.unsplash.com/photo-1603095859718-b6300a0aad18?auto=format&fit=crop&w=1200&q=82",light:"Luz indirecta brillante",water:"Medio · al secarse 3–4 cm",season:"Mayor crecimiento en primavera–verano",difficulty:"Fácil",petNote:"Tóxica para perros y gatos si se mastica.",description:"Follaje tropical de gran presencia. Disfruta de ambientes cálidos, luminosos y sin sol fuerte; en Melipilla conviene protegerla del frío."},
 {id:"sansevieria",name:"Lengua de suegra",botanical:"Dracaena trifasciata",category:"Interior",price:7990,image:"https://images.unsplash.com/photo-1570796119960-7df4b70dc202?auto=format&fit=crop&w=1200&q=82",light:"De luz baja a indirecta brillante",water:"Bajo · dejar secar por completo",season:"Todo el año",difficulty:"Muy fácil",petNote:"Tóxica para perros y gatos si se ingiere.",description:"Una planta resistente y escultórica para interiores. Su principal cuidado es evitar el exceso de agua, especialmente durante el invierno."},
 {id:"poto",name:"Poto",botanical:"Epipremnum aureum",category:"Interior",price:5490,image:"https://images.unsplash.com/photo-1595524147656-eb5d0a63e9a9?auto=format&fit=crop&w=1200&q=82",light:"Luz indirecta · tolera luz baja",water:"Medio · al secarse la capa superior",season:"Todo el año",difficulty:"Muy fácil",petNote:"Tóxico para perros y gatos si se mastica.",description:"Trepadora o colgante de crecimiento generoso. Ideal para comenzar: se adapta a distintos espacios y avisa con sus hojas cuando necesita agua."},
 {id:"ficus",name:"Ficus gomero",botanical:"Ficus elastica ‘Robusta’",category:"Interior",price:14990,image:"https://images.unsplash.com/photo-1687579520873-19a04c4eb297?auto=format&fit=crop&w=1200&q=82",light:"Luz indirecta brillante",water:"Medio · dejar secar parcialmente",season:"Mayor crecimiento en primavera–verano",difficulty:"Intermedia",petNote:"La savia es irritante para personas y mascotas.",description:"Hojas amplias, oscuras y brillantes para espacios interiores. Mantener lejos de corrientes frías y girar la maceta para un crecimiento equilibrado."},
 {id:"limonero",name:"Limonero",botanical:"Citrus × limon",category:"Huerto",price:18990,image:"https://images.unsplash.com/photo-1705616459154-c27e86bcd994?auto=format&fit=crop&w=1200&q=82",light:"Sol directo",water:"Medio · riego profundo",season:"Fruto según variedad, común en otoño–invierno",difficulty:"Intermedia",petNote:"Evitar que mascotas ingieran hojas, cáscaras o aceites.",description:"Frutal aromático para patio o suelo. Produce mejor con abundante sol, nutrición en época de crecimiento y protección frente a heladas cuando es joven."},
 {id:"romero",name:"Romero",botanical:"Salvia rosmarinus",category:"Huerto",price:4490,image:"https://images.unsplash.com/photo-1515586000433-45406d8e6662?auto=format&fit=crop&w=1200&q=82",light:"Sol directo",water:"Bajo · dejar secar entre riegos",season:"Floración frecuente invierno–primavera",difficulty:"Fácil",petNote:"Considerado no tóxico para perros y gatos.",description:"Aromático, culinario y perfecto para un jardín mediterráneo. Prefiere suelo pobre pero muy drenante y riegos espaciados una vez establecido."}
];
export const formatCLP=(value:number)=>new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0}).format(value);
export const STORE={phoneDisplay:"+56 9 8371 6033",phoneWhatsApp:"56983716033",maps:"https://maps.app.goo.gl/wjieYd9z7JWRjZmg8",address:"Unnamed Road, Melipilla, Región Metropolitana",rating:"4,6",reviews:"81 opiniones",hours:"Lun–sáb · 08:00–12:00 / 14:00–17:30"};
