<?php
declare(strict_types=1);require __DIR__.'/common.php';require_auth();$method=$_SERVER['REQUEST_METHOD']??'GET';$pdo=db();
if($method==='GET'){$plants=$pdo->query('SELECT id,name,botanical,category,price,image,light,water,season,difficulty,pet_note AS petNote,description FROM plants WHERE published=1 ORDER BY position,name')->fetchAll();foreach($plants as &$p)$p['price']=$p['price']===null?null:(int)$p['price'];$settings=[];foreach($pdo->query('SELECT setting_key,setting_value FROM site_settings')->fetchAll()as$row)$settings[$row['setting_key']]=$row['setting_value'];$faqs=$pdo->query('SELECT id,question,answer,position FROM faqs WHERE published=1 ORDER BY position,id')->fetchAll();respond(['plants'=>$plants,'settings'=>$settings,'faqs'=>$faqs]);}
require_csrf();$resource=$_GET['resource']??'';$input=body();
if($resource==='plants'&&$method==='PUT'){$required=['id','name','category','image'];foreach($required as$key)if(trim((string)($input[$key]??''))==='')respond(['error'=>'Completa nombre, categoría e imagen.'],422);$sql='INSERT INTO plants(id,name,botanical,category,price,image,light,water,season,difficulty,pet_note,description,published,position) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,1,COALESCE((SELECT MAX(p.position)+1 FROM plants p),0)) ON DUPLICATE KEY UPDATE name=VALUES(name),botanical=VALUES(botanical),category=VALUES(category),price=VALUES(price),image=VALUES(image),light=VALUES(light),water=VALUES(water),season=VALUES(season),difficulty=VALUES(difficulty),pet_note=VALUES(pet_note),description=VALUES(description),published=1';$pdo->prepare($sql)->execute([$input['id'],$input['name'],$input['botanical']??'',$input['category'],$input['price']===''?null:($input['price']??null),$input['image'],$input['light']??'',$input['water']??'',$input['season']??'',$input['difficulty']??'',$input['petNote']??'',$input['description']??'']);respond(['ok'=>true]);}
if($resource==='plants'&&$method==='DELETE'){$pdo->prepare('DELETE FROM plants WHERE id=?')->execute([(string)($_GET['id']??'')]);respond(['ok'=>true]);}
if($resource==='settings'&&$method==='PUT'){$stmt=$pdo->prepare('INSERT INTO site_settings(setting_key,setting_value) VALUES(?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)');$pdo->beginTransaction();foreach($input as$key=>$value)if(is_string($key)&&is_scalar($value))$stmt->execute([$key,(string)$value]);$pdo->commit();respond(['ok'=>true]);}
if($resource==='faqs'&&$method==='PUT'){$pdo->beginTransaction();$pdo->exec('DELETE FROM faqs');$stmt=$pdo->prepare('INSERT INTO faqs(question,answer,position,published) VALUES(?,?,?,1)');foreach($input as$i=>$faq)$stmt->execute([(string)($faq['question']??''),(string)($faq['answer']??''),(int)$i]);$pdo->commit();respond(['ok'=>true]);}
if($resource==='bootstrap'&&$method==='POST'){$count=(int)$pdo->query('SELECT COUNT(*) FROM plants')->fetchColumn();if($count>0)respond(['error'=>'La base ya contiene plantas.'],409);$pdo->beginTransaction();$ps=$pdo->prepare('INSERT INTO plants(id,name,botanical,category,price,image,light,water,season,difficulty,pet_note,description,published,position) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,1,?)');foreach(($input['plants']??[])as$i=>$p)$ps->execute([$p['id'],$p['name'],$p['botanical']??'',$p['category'],$p['price']??null,$p['image'],$p['light']??'',$p['water']??'',$p['season']??'',$p['difficulty']??'',$p['petNote']??'',$p['description']??'',(int)$i]);$ss=$pdo->prepare('INSERT INTO site_settings(setting_key,setting_value) VALUES(?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)');foreach(($input['settings']??[])as$k=>$v)$ss->execute([$k,(string)$v]);$fs=$pdo->prepare('INSERT INTO faqs(question,answer,position,published) VALUES(?,?,?,1)');foreach(($input['faqs']??[])as$i=>$f)$fs->execute([$f['question'],$f['answer'],(int)$i]);$pdo->commit();respond(['ok'=>true]);}
respond(['error'=>'Operación no válida.'],404);
