CREATE TABLE IF NOT EXISTS admin_users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(190) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS plants (
  id VARCHAR(120) PRIMARY KEY,
  name VARCHAR(190) NOT NULL,
  botanical VARCHAR(190) NOT NULL DEFAULT '',
  category VARCHAR(100) NOT NULL,
  price INT UNSIGNED NULL,
  image TEXT NOT NULL,
  light VARCHAR(255) NOT NULL DEFAULT '', water VARCHAR(255) NOT NULL DEFAULT '',
  season VARCHAR(255) NOT NULL DEFAULT '', difficulty VARCHAR(100) NOT NULL DEFAULT '',
  pet_note TEXT NOT NULL, description TEXT NOT NULL,
  published TINYINT(1) NOT NULL DEFAULT 1, position INT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS site_settings (
  setting_key VARCHAR(100) PRIMARY KEY, setting_value TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS faqs (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, question TEXT NOT NULL, answer TEXT NOT NULL,
  position INT NOT NULL DEFAULT 0, published TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
